/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.App.AppElement;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class StorePanel extends javax.swing.JPanel {
    
    private final List<AppUnit> appUnits;

    /**
     * Creates new form StorePanel
     */
    public StorePanel() {
        this.appUnits = new ArrayList<>();
        initComponents();
    }
    
    public void setGridZise(int rows, int columns) {
        this.removeAll();
        this.setLayout(new GridLayout(rows, columns, 5, 10));
        AppUnit appUnit;
        for (int i = 0; i < rows * columns; i++) {
            appUnit = new AppUnit();
            this.add(appUnit);
            this.appUnits.add(appUnit);
        }
        this.validate();
    }
    
    boolean addApps(List<AppElement> apps) {
        for (AppElement app : apps) {
            if (!addApp(apps.indexOf(app), app)) {
                return false;
            }
        }
        return true;
    }
    
    boolean addApp(int index, AppElement paramater) {
        if (index >= this.appUnits.size() || index < 0) {
            return false;
        }
        AppUnit appUnit = this.appUnits.get(index);
        appUnit.setAppParameter(paramater);
        appUnit.display();
        this.updateUI();
        return true;
    }
    
    public void display() {
        this.validate();
        for (AppUnit appUnit : appUnits) {
            appUnit.display();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
